;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Fri May 17 2019
; Processor: ATmega16
; Compiler:  AVRASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      rjmp  Start

;====================================================================
; CODE SEGMENT
;====================================================================

Start:
      ; make PORTD output
      ldi r16,0xFF
      out DDRD,r16
      
      ;ACME = 1
      in r16,SFIOR
      ori r16,0b00001000
      out SFIOR,r16
      
      ;ACD = 0 , ACBG = 0
      in r16,ACSR
      andi r16,0b00111111
      out ACSR,r16
      
      ;ADEN = 0
      in r16,ADCSRA
      andi r16,0b01111111
      out ADCSRA,r16
      
      ;MUX = 001 (ADC1)
      in r16,ADMUX
      ori r16,0b00000001
      out ADMUX,r16
      in r16,ADMUX
      andi r16,0b11111001
      out ADMUX,r16
      
      
Loop:
      in r16,ACSR
      ;check ACO if equals 1 run routine else skip
      sbrs r16,5
	 call TURN_ON
      rjmp  Loop

TURN_ON:
      ldi r16,0x20
      out PORTD,r16
ret
;====================================================================
