;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Thu Apr 11 2019
; Processor: ATmega16
; Compiler:  AVRASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector

;====================================================================
; CODE SEGMENT
;====================================================================

.org 0x00
jmp init
init:
	; initialize stack pointer
	LDI	R16, low(RAMEND)
	OUT	SPL, R16
	LDI	R16, high(RAMEND)
	OUT	SPH, R16
	 
	ldi r16,0xFF
	out DDRD,r16
	
	ldi r16,0x00 ; counter of patterns
	
	ldi r17, 0x26 ; student number 9631014
	
	mov r10,r17 ; r10 contains student code
	ldi r18,0b10100000 ; contains pattern
	and r10,r18
	cp r10,r18
	in r19,SREG
	sbrc r19, 1
	inc r16
	
	mov r10,r17 ; r10 contains student code
	ldi r18,0b01010000
	and r10,r18
	cp r10,r18
	in r19,SREG
	sbrc r19, 1
	inc r16
	
	mov r10,r17 ; r10 contains student code
	ldi r18,0b00101000
	and r10,r18
	cp r10,r18
	in r19,SREG
	sbrc r19, 1
	inc r16
	
	mov r10,r17 ; r10 contains student code
	ldi r18,0b00010100
	and r10,r18
	cp r10,r18
	in r19,SREG
	sbrc r19, 1
	inc r16
	
	mov r10,r17 ; r10 contains student code
	ldi r18,0b00001010
	and r10,r18
	cp r10,r18
	in r19,SREG
	sbrc r19, 1
	inc r16
	
	mov r10,r17 ; r10 contains student code
	ldi r18,0b00000101
	and r10,r18
	cp r10,r18
	in r19,SREG
	sbrc r19, 1
	inc r16
	
	out PORTD,r16  
jmp loop

loop:
	out PORTD,r16
jmp loop



;====================================================================
